---
collections:
  - name: amazon.aws 
    version: 1.2.1
  
  - name: ansible.netcommon
    version: 1.4.1

  - name: azure.azcollection
    version: 1.2.0

  - name: cisco.aci
    version: 1.1.1
  
  - name: cisco.ios
    version: 1.2.1

  - name: cisco.nxos
    version: 1.3.1

  - name: clay584.genie
    version: 0.1.11

  - name: netbox.netbox
    version: 1.1.0
